### ISSUE TITLE
any chance this works behind windows lockscreen ?!

### ISSUE THREAD

**Issue by tuqqo** [sophice/ahk-keyboard-locker#6]
hello!
hotkeys/shortcuts usually dont work on the windows lockscreen. 
so, can it be done with autohotkey?
thanks

**Comment by sophice** [comment]
Easy way to find out - try!

I just did a quick test myself. The keyboard shortcut for locking does not work on the log in screen. However, if it is already locked and then you go to the login screen, then it seems to continue to block key presses and also seems to accept the password input for unlocking.

The intended use for this script isn't security so locking out the login screen is not an intended function that I would want to build and support, but if you know a way to do it that doesn't interfere with existing functions, you're welcome to submit a PR!

I did some quick searching and it seems that regular keyboard shortcuts will not pass through the login screen to scripts, but apparently I can still capture key presses since the unlock password worked, and I've read that certain other inputs (like joystick) also get through. So it seems like it should be possible to toggle the lock on, from the log in screen, if you figure out what inputs get through to it and use those.

Up to you if you feel like trying in a PR.

**Comment by tuqqo** [comment]
hello. i might have phrased my question wrong.

i tried it beforehand and actually wanted to ask if it is possible to make the shortcut-combo available on the lock screen.
the reason for my question is, i want every key on the lock screen locked, so i can clean my keyboard without entering the "forget-password" screen. this is messing up with screen scaling and volume and some other things. every time my window positions and sizes are getting messed up on both of my monitors. 

its just in my routine that i regularly clean my keyboard before starting a work-session, and as soon as i wake up the laptop by pressing the keys during cleaning, the first thing seen is the lock-screen. so it would be great if i then can instantly lock all keys.

but actually never mind, cause i can just unlock the screen and open the script, and then clean my keyboard.
i was thinking to complicated and asked out of curiosity if shortcut-combos are somehow possible on lock-screen.

but thanks for your fast and detailed reply, i appreciate it.

**Comment by sophice** [comment]
Oh OK, I see, That is exactly the use case for this. I also wipe down my workstation daily and have used this for a number of years for that purpose. I do what you say, log in and then lock the keyboard with this script, so that I can read an article or watch a YouTube video while cleaning and getting settled.

There is a known issue with this script (at least with my keyboard) that certain functions somehow, but rarely, get through if you're swiping too many keys at once while cleaning it. Let me know if you find this happens to you. I haven't looked in to it yet as it just hasn't been a major issue for me, but I plan to eventually try to figure it out.
